sudo: false

language: python

python:
  - "3.5"

# Test a sampling of combinations
env:
  - TOXENV=py27-1.7
  - TOXENV=py27-1.8
  - TOXENV=py27-1.10
  - TOXENV=py27-1.11
  - TOXENV=py34-1.7
  - TOXENV=py34-1.8
  - TOXENV=py34-1.11
  - TOXENV=py35-1.9
  - TOXENV=py35-1.10
  - TOXENV=py35-1.11
  - TOXENV=py36-1.8
  - TOXENV=py36-1.10
  - TOXENV=py36-1.11

install:
  - pip install tox

script:
  - tox
#
#matrix:
#  allow_failures:
#    - env: TOXENV=py27-trunk,py33-trunk
