language: python

python:
  - "3.6"

# Test a sampling of combinations
env:
  - TOXENV=py27-1.7,py34-1.7
  - TOXENV=py27-1.8,py34-1.8,py36-1.8
  - TOXENV=py27-1.9,py35-1.9
  - TOXENV=py27-1.10,py35-1.10,py36-1.10
  - TOXENV=py27-1.11,py34-1.11,py35-1.11,py36-1.11

install:
  - pip install tox

script:
  - tox
#
#matrix:
#  allow_failures:
#    - env: TOXENV=py27-trunk,py33-trunk
